//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer_response
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public answer_response()
        {
            this.thong_ke_theo_yeu_cau = new HashSet<thong_ke_theo_yeu_cau>();
        }
    
        public int id { get; set; }
        public int surveyID { get; set; }
        public Nullable<int> id_users { get; set; }
        public Nullable<int> id_cbvc_khao_sat { get; set; }
        public Nullable<int> id_nguoi_hoc_khao_sat { get; set; }
        public Nullable<int> id_nguoi_hoc_co_hp_khao_sat { get; set; }
        public Nullable<int> id_ctdt { get; set; }
        public string email { get; set; }
        public string json_answer { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<int> id_namhoc { get; set; }
    
        public virtual cbvc_khao_sat cbvc_khao_sat { get; set; }
        public virtual ctdt ctdt { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual nguoi_hoc_dang_co_hoc_phan nguoi_hoc_dang_co_hoc_phan { get; set; }
        public virtual nguoi_hoc_khao_sat nguoi_hoc_khao_sat { get; set; }
        public virtual survey survey { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thong_ke_theo_yeu_cau> thong_ke_theo_yeu_cau { get; set; }
    }
}
