//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bo_mon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bo_mon()
        {
            this.ctdt = new HashSet<ctdt>();
        }
    
        public int id_bo_mon { get; set; }
        public string ten_bo_mon { get; set; }
        public Nullable<int> id_khoa { get; set; }
        public Nullable<int> ngay_tao { get; set; }
        public Nullable<int> ngay_cap_nhat { get; set; }
    
        public virtual khoa khoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctdt> ctdt { get; set; }
    }
}
