//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbSurveyEntities : DbContext
    {
        public dbSurveyEntities()
            : base("name=dbSurveyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<answer_response> answer_response { get; set; }
        public virtual DbSet<CanBoVienChuc> CanBoVienChuc { get; set; }
        public virtual DbSet<chuc_nang_users> chuc_nang_users { get; set; }
        public virtual DbSet<ChucVu> ChucVu { get; set; }
        public virtual DbSet<ctdt> ctdt { get; set; }
        public virtual DbSet<DonVi> DonVi { get; set; }
        public virtual DbSet<group_mon_hoc> group_mon_hoc { get; set; }
        public virtual DbSet<hedaotao> hedaotao { get; set; }
        public virtual DbSet<hoc_ky> hoc_ky { get; set; }
        public virtual DbSet<hoc_phan> hoc_phan { get; set; }
        public virtual DbSet<khoa> khoa { get; set; }
        public virtual DbSet<LoaiKhaoSat> LoaiKhaoSat { get; set; }
        public virtual DbSet<lop> lop { get; set; }
        public virtual DbSet<mon_hoc> mon_hoc { get; set; }
        public virtual DbSet<NamHoc> NamHoc { get; set; }
        public virtual DbSet<nguoi_hoc_dang_co_hoc_phan> nguoi_hoc_dang_co_hoc_phan { get; set; }
        public virtual DbSet<phan_quyen_chuc_nang_users> phan_quyen_chuc_nang_users { get; set; }
        public virtual DbSet<sinhvien> sinhvien { get; set; }
        public virtual DbSet<survey> survey { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<thong_ke_theo_yeu_cau> thong_ke_theo_yeu_cau { get; set; }
        public virtual DbSet<typeusers> typeusers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
