//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class group_mon_hoc
    {
        public int id_group_mh { get; set; }
        public string ten_group_mh { get; set; }
        public int ngay_tao { get; set; }
        public int ngay_cap_nhat { get; set; }
    }
}
