//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nguoi_hoc_dang_co_hoc_phan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nguoi_hoc_dang_co_hoc_phan()
        {
            this.thong_ke_theo_yeu_cau = new HashSet<thong_ke_theo_yeu_cau>();
        }
    
        public int id_nguoi_hoc_by_hoc_phan { get; set; }
        public Nullable<int> surveyID { get; set; }
        public int id_mon_hoc { get; set; }
        public int id_sinh_vien { get; set; }
        public Nullable<int> id_dot_khao_sat { get; set; }
        public Nullable<int> id_giang_vvien { get; set; }
        public string thang_by_hoc_phan { get; set; }
        public Nullable<int> da_khao_sat { get; set; }
    
        public virtual CanBoVienChuc CanBoVienChuc { get; set; }
        public virtual dot_khao_sat dot_khao_sat { get; set; }
        public virtual mon_hoc mon_hoc { get; set; }
        public virtual sinhvien sinhvien { get; set; }
        public virtual survey survey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<thong_ke_theo_yeu_cau> thong_ke_theo_yeu_cau { get; set; }
    }
}
