//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class radio_cau_hoi
    {
        public int id_radio_cau_hoi { get; set; }
        public Nullable<int> thu_tu { get; set; }
        public string ten_radio_cau_hoi { get; set; }
        public Nullable<int> id_group_radio { get; set; }
    
        public virtual group_radio_cau_hoi group_radio_cau_hoi { get; set; }
    }
}
