//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinhvien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sinhvien()
        {
            this.answer_response = new HashSet<answer_response>();
        }
    
        public int id_sv { get; set; }
        public int id_lop { get; set; }
        public string ma_sv { get; set; }
        public string hovaten { get; set; }
        public Nullable<System.DateTime> ngaysinh { get; set; }
        public string sodienthoai { get; set; }
        public string diachi { get; set; }
        public string phai { get; set; }
        public string namtotnghiep { get; set; }
        public Nullable<int> ngaycapnhat { get; set; }
        public Nullable<int> ngaytao { get; set; }
        public Nullable<bool> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_response> answer_response { get; set; }
        public virtual lop lop { get; set; }
    }
}
