//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class survey
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public survey()
        {
            this.answer_response = new HashSet<answer_response>();
        }
    
        public int surveyID { get; set; }
        public int id_hedaotao { get; set; }
        public string surveyData { get; set; }
        public string surveyTitle { get; set; }
        public string surveyDescription { get; set; }
        public Nullable<int> surveyTimeStart { get; set; }
        public Nullable<int> surveyTimeEnd { get; set; }
        public Nullable<int> surveyTimeMake { get; set; }
        public Nullable<int> surveyTimeUpdate { get; set; }
        public Nullable<bool> surveyStatus { get; set; }
        public int id_loaikhaosat { get; set; }
        public Nullable<int> creator { get; set; }
        public Nullable<int> id_namhoc { get; set; }
        public string key_class { get; set; }
        public string doi_tuong_dat_biet { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<answer_response> answer_response { get; set; }
        public virtual hedaotao hedaotao { get; set; }
        public virtual LoaiKhaoSat LoaiKhaoSat { get; set; }
        public virtual NamHoc NamHoc { get; set; }
        public virtual users users { get; set; }
    }
}
