//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class thong_bao_loi
    {
        public int id_ma_loi { get; set; }
        public string tieu_de_ma_loi { get; set; }
        public string noi_dung_ma_loi { get; set; }
        public int ngay_gui_loi { get; set; }
        public int ngay_khac_phuc { get; set; }
    }
}
